version: "3.6"

networks:
  previewer:

services:
  ipreviewer:
    container_name: ipreviewer
    build:
      context: .
      dockerfile: server.dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - CACHE_CAPACITY=${CACHE_CAPACITY}
    networks:
      - previewer

  nginx:
    container_name: ipreviewer_nginx
    image: nginx:1.21.4
    ports:
      - "80:80"
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "ipreviewer"
    networks:
      - previewer