version: "3.6"

networks:
  previewer:

services:
  ipreviewer:
    container_name: ipreviewer
    image: alpine:latest
    ports:
      - "8080:8080"
    volumes:
      - ./bin:/var/www
    environment:
      - CACHE_CAPACITY=${CACHE_CAPACITY}
    command:
      - ./var/www/server
    networks:
      - previewer

  nginx:
    container_name: ipreviewer_nginx
    image: nginx:1.21.4
    ports:
      - "80:80"
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "ipreviewer"
    networks:
      - previewer