// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_image_previewer is a generated GoMock package.
package mocks

import (
	context "context"
	image_previewer "image-previewer/pkg/imagepreviewer"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mocks of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mocks recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mocks instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Resize mocks base method.
func (m *MockService) Resize(ctx context.Context, width, height int, url string) (*image_previewer.ResizeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", ctx, width, height, url)
	ret0, _ := ret[0].(*image_previewer.ResizeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resize indicates an expected call of Resize.
func (mr *MockServiceMockRecorder) Resize(ctx, width, height, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockService)(nil).Resize), ctx, width, height, url)
}
