name: golangci-lint
on:
  push:
    branches:
      - master
      - dev
jobs:
  go_get:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.41.1

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v -count=100 -race -timeout=5m ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Calc coverage
        run: go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.5
      - name: Coveralls
        uses: coverallsapp/github-action@v1.0.4